const ri=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const pick=a=>a[ri(0,a.length-1)];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=ri(0,i);[a[i],a[j]]=[a[j],a[i]];}return a};
function mcq(prompt,expression,answer,distractors,explanation){return {type:"choice",prompt,expression,answer,choices:shuffle([...new Set([answer,...distractors])]).slice(0,4),explanation};}
function text(prompt,expression,answer,explanation,acceptedAnswers=[]){return {type:"text",prompt,expression,answer,acceptedAnswers:[answer,...acceptedAnswers],explanation};}
function l1(){const items=[
 ["Chiều cao của mỗi học sinh trong lớp","Dữ liệu định lượng",["Dữ liệu định tính","Dữ liệu không hợp lệ","Không phải dữ liệu"]],
 ["Màu sắc yêu thích của học sinh","Dữ liệu định tính",["Dữ liệu định lượng","Dữ liệu liên tục","Không phải dữ liệu"]],
 ["Số quyển sách mỗi bạn đọc trong tháng","Dữ liệu định lượng",["Dữ liệu định tính","Dữ liệu mô tả","Không phải dữ liệu"]],
 ["Phương tiện đến trường của học sinh","Dữ liệu định tính",["Dữ liệu định lượng","Dữ liệu số","Không phải dữ liệu"]]
 ];const [e,a,d]=pick(items);return mcq("Xác định loại dữ liệu:",e,a,d,"Dữ liệu định tính mô tả đặc điểm hoặc nhóm; dữ liệu định lượng được biểu diễn bằng số đo hoặc số đếm.");}
function l2(){const vals=Array.from({length:10},()=>ri(1,5)), target=pick(vals), count=vals.filter(x=>x===target).length;return text(`Dãy số liệu là: ${vals.join(", ")}. Tính tần số của giá trị ${target}.`,"",String(count),`Giá trị ${target} xuất hiện ${count} lần nên tần số bằng ${count}.`);}
function l3(){const months=["Tháng 1","Tháng 2","Tháng 3","Tháng 4","Tháng 5"], vals=months.map(()=>ri(20,80)); const mode=ri(1,3); if(mode===1){const i=ri(0,4);return text("Biểu đồ đoạn thẳng ghi số cây trồng được theo tháng:",months.map((m,j)=>`${m}: ${vals[j]} cây`).join("; ")+`. Hỏi ${months[i]} trồng được bao nhiêu cây?`,String(vals[i]),`Đọc đúng điểm ứng với ${months[i]} được ${vals[i]} cây.`)} if(mode===2){const mx=Math.max(...vals),i=vals.indexOf(mx);return mcq("Tháng nào có giá trị lớn nhất?",months.map((m,j)=>`${m}: ${vals[j]}`).join("; "),months[i],months.filter((_,j)=>j!==i).slice(0,3),`${months[i]} có ${mx}, là giá trị lớn nhất.`)} const diff=vals[4]-vals[0];return text("Tính mức thay đổi từ tháng đầu đến tháng cuối:",`${months[0]}: ${vals[0]}; ${months[4]}: ${vals[4]}`,String(diff),`Lấy ${vals[4]} - ${vals[0]} = ${diff}.`);}
function l4(){const parts=[10,15,20,25,30,35,40,45,50], pct=pick(parts), total=pick([40,80,100,120,200]); const mode=ri(1,2);if(mode===1)return text("Một thành phần chiếm tỉ lệ sau trong biểu đồ quạt tròn. Tính số đo góc ở tâm:",`${pct}%`,String(pct*3.6),`${pct}% × 360° = ${pct*3.6}°.`,[`${pct*3.6}°`]);const count=total*pct/100;if(Number.isInteger(count))return text("Một nhóm chiếm tỉ lệ trong tổng số. Tính số phần tử của nhóm:",`${pct}% của ${total}`,String(count),`${total} × ${pct}/100 = ${count}.`);return l4();}
function l5(){const cases=[
 ["Thể hiện nhiệt độ thay đổi trong 7 ngày","Biểu đồ đoạn thẳng",["Biểu đồ hình quạt tròn","Bảng chữ cái","Sơ đồ cây"]],
 ["Thể hiện tỉ lệ các loại sách trong thư viện","Biểu đồ hình quạt tròn",["Biểu đồ đoạn thẳng","Trục số","Sơ đồ đoạn thẳng"]],
 ["Ghi lại số học sinh chọn từng câu lạc bộ","Bảng thống kê",["Biểu đồ đoạn thẳng bắt buộc","Bản đồ","Hình chiếu"]]
 ];const [e,a,d]=pick(cases);return mcq("Chọn cách biểu diễn phù hợp nhất:",e,a,d,`${a} phù hợp nhất với mục đích được nêu.`);}
function l6(){const a=ri(20,60),b=ri(20,60),c=ri(20,60), vals={"Lớp 8A":a,"Lớp 8B":b,"Lớp 8C":c};const names=Object.keys(vals),mx=Math.max(a,b,c),mn=Math.min(a,b,c);if(ri(1,2)===1){const best=names.find(n=>vals[n]===mx);return mcq("Dựa vào số liệu, lớp nào có giá trị lớn nhất?",names.map(n=>`${n}: ${vals[n]}`).join("; "),best,names.filter(n=>n!==best).concat(["Không xác định"]),`${best} có ${mx}, lớn nhất trong ba lớp.`)}return text("Tính khoảng chênh lệch giữa giá trị lớn nhất và nhỏ nhất:",names.map(n=>`${n}: ${vals[n]}`).join("; "),String(mx-mn),`Khoảng chênh lệch là ${mx} - ${mn} = ${mx-mn}.`);}
function l7(){const total=pick([40,80,100,120]), a=pick([10,20,25,30,40,50]), count=total*a/100;if(!Number.isInteger(count))return l7(); const rest=total-count; const mode=ri(1,3);if(mode===1)return text("Một khảo sát có số người chọn phương án A như sau. Tính số người không chọn A:",`Tổng ${total} người; A chiếm ${a}%`,String(rest),`Số chọn A là ${count}; số còn lại ${total}-${count}=${rest}.`);if(mode===2)return text("Tính góc quạt biểu diễn phương án A:",`A chiếm ${a}%`,String(a*3.6),`${a}% × 360° = ${a*3.6}°.`,[`${a*3.6}°`]);return mcq("Loại biểu đồ nào phù hợp để thể hiện cơ cấu hai nhóm A và còn lại?",`A: ${a}%; còn lại: ${100-a}%`,"Biểu đồ hình quạt tròn",["Biểu đồ đoạn thẳng","Trục số","Bảng nhân"],"Cơ cấu các phần trong một tổng thể phù hợp với biểu đồ hình quạt tròn.");}
export function generateQuestion(level){return [l1,l2,l3,l4,l5,l6,l7][level]();}
